// Country → Currency, Tax Rate, Tax Name, Payment Methods
// Used by Super Admin when creating a store AND by POS for default tax
export const COUNTRY_CONFIG = {
  'Pakistan': {
    currency: 'PKR',
    symbol: '₨',
    tax: 0,
    taxName: 'Sales Tax',
    paymentMethods: ['cash', 'mobile_wallet', 'bank_transfer', 'card'],
    mobileWalletLabel: 'JazzCash / EasyPaisa',
  },
  'India': {
    currency: 'INR',
    symbol: '₹',
    tax: 18,
    taxName: 'GST',
    paymentMethods: ['cash', 'mobile_wallet', 'bank_transfer', 'card'],
    mobileWalletLabel: 'UPI / Paytm',
  },
  'UAE': {
    currency: 'AED',
    symbol: 'د.إ',
    tax: 5,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'Apple Pay / Google Pay',
  },
  'Saudi Arabia': {
    currency: 'SAR',
    symbol: '﷼',
    tax: 15,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'bank_transfer', 'mobile_wallet'],
    mobileWalletLabel: 'STC Pay / Apple Pay',
  },
  'Qatar': {
    currency: 'QAR',
    symbol: 'ر.ق',
    tax: 0,
    taxName: 'No Tax',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'Apple Pay',
  },
  'Egypt': {
    currency: 'EGP',
    symbol: 'ج.م',
    tax: 14,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'bank_transfer', 'mobile_wallet'],
    mobileWalletLabel: 'Vodafone Cash / Fawry',
  },
  'USA': {
    currency: 'USD',
    symbol: '$',
    tax: 8.5,
    taxName: 'Sales Tax',
    paymentMethods: ['cash', 'card', 'mobile_wallet', 'bank_transfer'],
    mobileWalletLabel: 'Apple Pay / Google Pay',
  },
  'UK': {
    currency: 'GBP',
    symbol: '£',
    tax: 20,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'mobile_wallet'],
    mobileWalletLabel: 'Apple Pay / Google Pay',
  },
  'Spain': {
    currency: 'EUR',
    symbol: '€',
    tax: 21,
    taxName: 'IVA (VAT)',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'Bizum',
  },
  'Germany': {
    currency: 'EUR',
    symbol: '€',
    tax: 19,
    taxName: 'MwSt (VAT)',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'Apple Pay / Google Pay',
  },
  'Kuwait': {
    currency: 'KWD',
    symbol: 'د.ك',
    tax: 0,
    taxName: 'No Tax',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'K-Net',
  },
  'Bahrain': {
    currency: 'BHD',
    symbol: '.د.ب',
    tax: 10,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'BenefitPay',
  },
  'Oman': {
    currency: 'OMR',
    symbol: 'ر.ع.',
    tax: 5,
    taxName: 'VAT',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'thawani',
  },
  'Jordan': {
    currency: 'JOD',
    symbol: 'د.ا',
    tax: 16,
    taxName: 'GST',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'CliQ',
  },
  'Turkey': {
    currency: 'TRY',
    symbol: '₺',
    tax: 18,
    taxName: 'KDV',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'PayTR',
  },
  'Canada': {
    currency: 'CAD',
    symbol: 'C$',
    tax: 13,
    taxName: 'HST / GST',
    paymentMethods: ['cash', 'card', 'bank_transfer'],
    mobileWalletLabel: 'Interac / Apple Pay',
  },
  'Australia': {
    currency: 'AUD',
    symbol: 'A$',
    tax: 10,
    taxName: 'GST',
    paymentMethods: ['cash', 'card', 'mobile_wallet'],
    mobileWalletLabel: 'Apple Pay / Google Pay',
  },
};

export const COUNTRY_NAMES = Object.keys(COUNTRY_CONFIG).sort();

export const getCountryConfig = (country) =>
  COUNTRY_CONFIG[country] || { currency: 'USD', symbol: '$', tax: 0, taxName: 'Tax' };
